### ISSUE TITLE
TODO for Github CI

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#1398]
- [ ] Build dyninst/tools on PR
- [x] Test building with clang on PR
- [ ] Add more OSes
    - [ ] Ubuntu 22
    - [ ] Fedora 36-38
    - [ ] OpenSUSE (used at ANL)
- [ ] Build base containers if and only if adding new OS or updating dep versions
- [ ] Update libabigail
    - [ ] automatically find latest branch to compare against (it's currently hard-coded)
    - [ ] test both .so and .a
- [ ] Release workflow
